# Generated by Django 2.2.2 on 2019-06-05 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_maxima', models.PositiveSmallIntegerField(verbose_name='Quantidade máxima de inscrições')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('info', models.TextField(blank=True, verbose_name='Informação')),
                ('url', models.URLField(blank=True, verbose_name='Link para mais informações')),
            ],
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('inicio', models.DateTimeField(verbose_name='Data e hora para início das inscrições')),
                ('resposta_textual', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'inscrições',
            },
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.IntegerField(blank=True, verbose_name='Matrícula')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('senha', models.CharField(max_length=32, verbose_name='Senha para inscrição')),
                ('turma', models.CharField(blank=True, max_length=128, verbose_name='Turma')),
                ('resposta', models.CharField(blank=True, max_length=255, verbose_name='Resposta')),
                ('alternativa', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='inscricao.Alternativa')),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='inscricao.Inscricao')),
            ],
        ),
        migrations.AddField(
            model_name='alternativa',
            name='inscricao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternativas', to='inscricao.Inscricao'),
        ),
    ]
