# Generated by Django 2.2.2 on 2019-06-05 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alternativa',
            name='info',
        ),
    ]
