# Generated by Django 2.2.2 on 2019-06-05 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0002_remove_alternativa_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alternativa',
            name='url',
        ),
    ]
