# Generated by Django 2.2.2 on 2019-06-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0004_alternativa_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativa',
            name='url',
            field=models.URLField(blank=True, default='', verbose_name='Link para mais informações'),
        ),
    ]
