# Generated by Django 2.2.2 on 2019-06-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0006_auto_20190605_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='matricula',
            field=models.IntegerField(blank=True, null=True, verbose_name='Matrícula'),
        ),
    ]
