# Generated by Django 2.2.2 on 2019-06-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0007_auto_20190605_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='resposta',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Resposta'),
        ),
    ]
