# Generated by Django 2.2.2 on 2019-06-05 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0008_auto_20190605_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='alternativa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='inscricao.Alternativa'),
        ),
    ]
