# Generated by Django 2.2.2 on 2019-06-05 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0009_auto_20190605_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='alternativa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='inscricao.Alternativa'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='turma',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Turma'),
        ),
    ]
