# Generated by Django 2.2.1 on 2019-06-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eletiva', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eletiva',
            name='professor',
        ),
        migrations.AddField(
            model_name='eletiva',
            name='professores',
            field=models.CharField(default='', max_length=255, verbose_name='Nomes dos professores da eletiva'),
        ),
        migrations.AlterField(
            model_name='eletiva',
            name='titulo',
            field=models.CharField(max_length=255, verbose_name='Título da eletiva'),
        ),
    ]
