# Generated by Django 2.2.2 on 2019-06-05 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eletiva', '0002_auto_20190604_2116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eletivaconfiguracao',
            options={'verbose_name_plural': 'configurações das eletivas'},
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do aluno')),
                ('matricula', models.CharField(max_length=255, verbose_name='Matrícula do aluno')),
                ('turma', models.CharField(max_length=128, verbose_name='Turma do aluno')),
                ('senha', models.CharField(max_length=32, verbose_name='Senha para o aluno')),
                ('configuracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='eletiva.EletivaConfiguracao')),
            ],
        ),
    ]
