# Generated by Django 2.2.2 on 2019-06-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eletiva', '0003_auto_20190605_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.CharField(blank=True, max_length=255, verbose_name='Matrícula do aluno'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='turma',
            field=models.CharField(blank=True, max_length=128, verbose_name='Turma do aluno'),
        ),
    ]
