# Generated by Django 2.2.2 on 2019-06-05 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eletiva', '0005_remove_aluno_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='eletiva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='eletiva.Eletiva'),
        ),
    ]
